export default {
  ENFP: "ENFP",
  INFP: "INFP",
  ENTP: "ENTP",
  INTP: "INTP",
  ESFJ: "ESFJ",
  ISFJ: "ISFJ",
  ESTJ: "ESTJ",
  ISTJ: "ISTJ",
  ENFJ: "ENFJ",
  INFJ: "INFJ",
  ESTP: "ESTP",
  ISTP: "ISTP",
  ESFP: "ESFP",
  ISFP: "ISFP",
  ENTJ: "ENTJ",
  INTJ: "INTJ",
};
